### ISSUE TITLE
Unexpected token A in JSON at position 4

### ISSUE THREAD

**Issue by sebasaezz** [Lenny4/get-sport-result#9]
I am an amateur at javascript, but i can provide the error, A:\Onde Drive\bot generico\ its my index.js file location but its actualy called botgen.js, i am using discord.js api but i dont think that this is relevant to the error.
Also, i have every dependency installed (and the dependencies of the dependencies)

```
(node:9492) UnhandledPromiseRejectionWarning: Error: Evaluation failed: SyntaxError: Unexpected token A in JSON at position 4
    at JSON.parse (<anonymous>)
    at __puppeteer_evaluation_script__:1:13
    at ExecutionContext._evaluateInternal (A:\OneDrive\bot generico\node_modules\get-sport-result\node_modules\puppeteer\lib\ExecutionContext.js:102:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async ExecutionContext.evaluate (A:\OneDrive\bot generico\node_modules\get-sport-result\node_modules\puppeteer\lib\ExecutionContext.js:33:16)
    at async Object.getJsonPuppeteer (A:\OneDrive\bot generico\node_modules\get-sport-result\src\supplier\sofascore.js:90:24)
    at async Object.getSoccer (A:\OneDrive\bot generico\node_modules\get-sport-result\src\supplier\sofascore.js:30:24)
    at async Object.get (A:\OneDrive\bot generico\node_modules\get-sport-result\src\supplier\sofascore.js:20:26)
    at async Object.get (A:\OneDrive\bot generico\node_modules\get-sport-result\src\app.js:45:26)
  -- ASYNC --
    at ExecutionContext.<anonymous> (A:\OneDrive\bot generico\node_modules\get-sport-result\node_modules\puppeteer\lib\helper.js:94:19)
    at DOMWorld.evaluate (A:\OneDrive\bot generico\node_modules\get-sport-result\node_modules\puppeteer\lib\DOMWorld.js:89:24)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
  -- ASYNC --
    at Frame.<anonymous> (A:\OneDrive\bot generico\node_modules\get-sport-result\node_modules\puppeteer\lib\helper.js:94:19)
    at Page.evaluate (A:\OneDrive\bot generico\node_modules\get-sport-result\node_modules\puppeteer\lib\Page.js:612:14)
    at Page.<anonymous> (A:\OneDrive\bot generico\node_modules\get-sport-result\node_modules\puppeteer\lib\helper.js:95:27)
    at Object.getJsonPuppeteer (A:\OneDrive\bot generico\node_modules\get-sport-result\src\supplier\sofascore.js:90:35)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.getSoccer (A:\OneDrive\bot generico\node_modules\get-sport-result\src\supplier\sofascore.js:30:24)
    at async Object.get (A:\OneDrive\bot generico\node_modules\get-sport-result\src\supplier\sofascore.js:20:26)
    at async Object.get (A:\OneDrive\bot generico\node_modules\get-sport-result\src\app.js:45:26)
(node:9492) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9492) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Lenny4** [comment]
@sebasaezz sorry for the late answer this package is not longer maintained.
